# Generated by Django 4.2.1 on 2023-06-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0005_alter_settings_options_alter_attempt_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='server_answer',
            field=models.CharField(blank=True, null=True, verbose_name='ответ сервера'),
        ),
    ]
